apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: andreistefanciprian/gomicropay-email:latest@sha256:435bd61280114318cf9649ac8e2880339bc1c9bb5cbe1c31a3851f10624c6fa6
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: email-secret
            - configMapRef:
                name: email-configmap