apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: andreistefanciprian/gomicropay-email:latest@sha256:73cb296cb3164a7053ea92d32da87dc72591558e716b3a6cc634886db3f1ceff
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: email-secret
            - configMapRef:
                name: email-configmap