apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    app: mysql-client
spec:
  containers:
    - name: mysql-client
      image: mysql:9.5@sha256:57c892ddeb17e6c7dddf219914db017b2cf3e2797806a75424444b83622cc8ef
      command: ["sleep", "infinity"]
